"""
grassflow init 命令

参考 opencode 的 /init 命令，初始化项目目录结构：
- 创建 .grass/config.json
- 创建 .grass/workflows/ 目录
- 可选：分析项目结构生成 AGENTS.md 规则文件
"""

import sys
from pathlib import Path
from typing import Optional

import click

from tui.display import display


def _analyze_project_structure(project_dir: Path) -> str:
    """分析项目结构，生成 AGENTS.md 内容"""
    lines = [
        "# AGENTS.md - Project Rules",
        "",
        f"Generated by GrassFlow for `{project_dir.name}`",
        "",
        "## Project Overview",
        "",
    ]

    # 检测项目类型
    indicators = {
        "Python": ["setup.py", "pyproject.toml", "requirements.txt", "Pipfile", "poetry.lock"],
        "Node.js": ["package.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb"],
        "Rust": ["Cargo.toml", "Cargo.lock"],
        "Go": ["go.mod", "go.sum"],
        "Java": ["pom.xml", "build.gradle", "gradlew", "settings.gradle"],
        "TypeScript": ["tsconfig.json"],
        "Web": ["index.html", "vite.config.js", "vite.config.ts", "next.config.js"],
    }

    detected = []
    for lang, files in indicators.items():
        for f in files:
            if (project_dir / f).exists():
                detected.append(lang)
                break

    if detected:
        lines.append(f"Detected project types: {', '.join(detected)}")
    else:
        lines.append("Project type: Unknown (no common indicators found)")

    lines.append("")

    # 列出关键目录
    lines.append("## Directory Structure")
    lines.append("")

    dirs_to_show = []
    for item in sorted(project_dir.iterdir()):
        if item.is_dir() and not item.name.startswith(".") and item.name not in ("__pycache__", "node_modules", "venv", ".venv", "dist", "build", "target"):
            dirs_to_show.append(item.name)

    if dirs_to_show:
        for d in dirs_to_show:
            lines.append(f"- `{d}/`")
    else:
        lines.append("- No notable directories found")

    lines.append("")

    # 列出关键文件
    lines.append("## Key Files")
    lines.append("")
    key_files = [f for f in ["README.md", "CONTRIBUTING.md", "LICENSE", "CHANGELOG.md", "Makefile", "Dockerfile"]
                 if (project_dir / f).exists()]
    if key_files:
        for f in key_files:
            lines.append(f"- `{f}`")
    else:
        lines.append("- No common key files found")

    lines.append("")
    lines.append("## GrassFlow Workflows")
    lines.append("")
    lines.append("Workflow definitions are stored in `.grass/workflows/`.")
    lines.append("Use `grassflow run <file.af>` to execute a workflow.")
    lines.append("")

    return "\n".join(lines)


def init_command(
    output: Optional[str] = None,
    force: bool = False,
) -> None:
    """
    初始化项目目录结构

    参考 opencode /init：
    - 创建 .grass/ 目录和配置文件
    - 可选生成 AGENTS.md

    Args:
        output: AGENTS.md 输出路径（如 --output AGENTS.md）
        force: 强制覆盖已有文件
    """
    project_dir = Path.cwd()
    grass_dir = project_dir / ".grass"
    config_file = grass_dir / "config.json"
    workflows_dir = grass_dir / "workflows"

    try:
        # 1. 创建 .grass/ 目录
        if not grass_dir.exists():
            grass_dir.mkdir(parents=True, exist_ok=True)
            display.print_success(f"Created {grass_dir}")
        else:
            display.print_info(f"{grass_dir} already exists")

        # 2. 创建 workflows/ 目录
        if not workflows_dir.exists():
            workflows_dir.mkdir(parents=True, exist_ok=True)
            display.print_success(f"Created {workflows_dir}")
        else:
            display.print_info(f"{workflows_dir} already exists")

        # 3. 创建 config.json（如不存在）
        if not config_file.exists() or force:
            import json
            default_config = {
                "version": "1.0.0",
                "provider": {},
                "llm": {
                    "default_model": "deepseek-v4-flash",
                    "default_provider": "deepseek",
                    "temperature": 0.7,
                    "max_tokens": 4096,
                    "timeout": 60,
                    "retry_count": 3,
                    "retry_delay": 1.0,
                },
                "workflow": {
                    "auto_save": True,
                    "auto_validate": True,
                    "max_parallel": 10,
                    "default_on_fail": "stop",
                    "execution_timeout": 300,
                },
                "display": {
                    "theme": "dark",
                    "show_timestamps": True,
                    "show_agent_names": True,
                    "log_level": "INFO",
                    "compact_mode": False,
                },
            }
            with open(config_file, "w", encoding="utf-8") as f:
                json.dump(default_config, f, indent=2, ensure_ascii=False)
            display.print_success(f"Created {config_file}")
        else:
            display.print_info(f"{config_file} already exists")

        # 4. 可选：生成 AGENTS.md
        if output:
            output_path = Path(output)
            if not output_path.is_absolute():
                output_path = project_dir / output_path

            if output_path.exists() and not force:
                display.print_info(f"{output_path} already exists. Use --force to overwrite.")
            else:
                content = _analyze_project_structure(project_dir)
                output_path.parent.mkdir(parents=True, exist_ok=True)
                with open(output_path, "w", encoding="utf-8") as f:
                    f.write(content)
                display.print_success(f"Generated {output_path}")

        # 5. 显示初始化摘要
        display.print_info("")
        display.print_success("Project initialized successfully!")
        display.print_info(f"  Config:  {config_file}")
        display.print_info(f"  Workflows: {workflows_dir}")
        display.print_info("")
        display.print_info("Next steps:")
        display.print_info("  grassflow config set llm.default_model gpt-4")
        display.print_info("  grassflow config api-key openai sk-xxx")
        display.print_info("  grassflow create <template_name>")

    except PermissionError as e:
        display.print_error(f"Permission denied: {e}")
        sys.exit(1)
    except Exception as e:
        display.print_error(f"Init failed: {e}")
        sys.exit(1)
